name: auto-format
on: pull_request
jobs:
  format:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Spotless format apply with Gradle Wrapper
        run: ./gradlew spotlessApply

      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Formatting Bot'
          git config --global user.email 'formatting-bot@no-domain.com'
          git remote set-url origin https://x-access-token:${{ secrets.FORMATTER_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "no-release: automated formatting changes"
          git push
